### ISSUE TITLE
Add a 'maven setup' notion

### ISSUE THREAD

**Issue by bstansberry** [overbaard/multi-repo-ci#34]
In the standard job (i.e. what runs if you don't have a .repo-config/components/xxx) add support for a 'mavenSetup' param.

Then use it like this in the normal Maven Build step.

```
mvn -V <mavenSetup>
mvn install <mavenOpts>
```

The -V results in a valid mvn execution regardless of whether 'mavenSetup' has a value.

The specific use case is testing new versions of jboss-parent-pom like this:

```
name: version plugin
components:
  - name: jboss-parent-pom
    org: jboss
    branch: 'main'
    mavenOpts: -DskipTests
  - name: jboss-marshalling
    org: jboss-remoting
    branch: 'main'
    mavenSetup: versions:update-parent -DallowSnapshots=true
    dependencies:
      - name: jboss-parent-pom
        property: version.unused
```

You can't use the version property trick to update a project's parent, but if you place versions:update-parent before install you can.

You could also test a new release version of the parent pom by skipping the local build and dropping the '-DallowSnapshots=true'

Of course, there may be other use cases.

N.B. The following won't work for the target use case as the parent pom version used in a maven process is the one read *before* whatever is in 'mavenSetup' executes.
 
```
mvn <mavenSetup> install <mavenOpts>
```
